using BillingService.Application.Interfaces;
using BillingService.Domain.Entities;
using BillingService.Domain.Enums;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace BillingService.Api.Services;

public class InvoicePdfGenerator : IInvoicePdfGenerator
{
    public byte[] Generate(Order order, Invoice invoice)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Element(c => ComposeHeader(c, order, invoice));
                page.Content().Element(c => ComposeContent(c, order));
                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by BillingService - ").FontSize(8).FontColor(Colors.Grey.Medium);
                    text.Span($"{DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC").FontSize(8).FontColor(Colors.Grey.Medium);
                });
            });
        });

        return document.GeneratePdf();
    }

    private static void ComposeHeader(IContainer container, Order order, Invoice invoice)
    {
        container.Row(row =>
        {
            row.RelativeItem().Column(col =>
            {
                col.Item().Text("INVOICE").FontSize(22).Bold();
                col.Item().PaddingTop(5).Text($"Invoice #: {invoice.InvoiceNumber}");
                col.Item().Text($"Order #: {order.OrderNumber}");
                col.Item().Text($"Date: {invoice.IssueDate:yyyy-MM-dd}");
            });

            row.ConstantItem(180).Column(col =>
            {
                col.Item().AlignRight().Text("Billing Service").Bold();
                col.Item().AlignRight().Text("Dhaka, Bangladesh").FontSize(9).FontColor(Colors.Grey.Darken1);
            });
        });
    }

    private static void ComposeContent(IContainer container, Order order)
    {
        container.PaddingVertical(20).Column(column =>
        {
            column.Spacing(18);

            column.Item().Element(c => ComposeCustomerInfo(c, order));
            column.Item().Element(c => ComposeItemsTable(c, order));
            column.Item().Element(c => ComposeTotals(c, order));
            column.Item().Element(c => ComposePaymentInfo(c, order));
        });
    }

    private static void ComposeCustomerInfo(IContainer container, Order order)
    {
        container.Column(col =>
        {
            col.Item().Text("Bill To").Bold();
            col.Item().Text(order.Customer?.Name ?? string.Empty);
            if (!string.IsNullOrWhiteSpace(order.Customer?.Phone))
                col.Item().Text(order.Customer.Phone);
            if (!string.IsNullOrWhiteSpace(order.Customer?.Address))
                col.Item().Text(order.Customer.Address);
        });
    }

    private static void ComposeItemsTable(IContainer container, Order order)
    {
        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(4);
                columns.RelativeColumn(1);
                columns.RelativeColumn(2);
                columns.RelativeColumn(2);
            });

            table.Header(header =>
            {
                header.Cell().Element(HeaderCell).Text("Product");
                header.Cell().Element(HeaderCell).AlignRight().Text("Qty");
                header.Cell().Element(HeaderCell).AlignRight().Text("Unit Price");
                header.Cell().Element(HeaderCell).AlignRight().Text("Line Total");

                static IContainer HeaderCell(IContainer c) =>
                    c.DefaultTextStyle(x => x.Bold())
                     .PaddingBottom(5)
                     .BorderBottom(1)
                     .BorderColor(Colors.Grey.Darken1);
            });

            foreach (var item in order.Items)
            {
                table.Cell().Element(Cell).Text(item.Product?.Name ?? string.Empty);
                table.Cell().Element(Cell).AlignRight().Text(item.Quantity.ToString());
                table.Cell().Element(Cell).AlignRight().Text(item.UnitPrice.ToString("N2"));
                table.Cell().Element(Cell).AlignRight().Text(item.LineTotal.ToString("N2"));

                static IContainer Cell(IContainer c) =>
                    c.PaddingVertical(5).BorderBottom(1).BorderColor(Colors.Grey.Lighten2);
            }
        });
    }

    private static void ComposeTotals(IContainer container, Order order)
    {
        container.AlignRight().Column(col =>
        {
            col.Item().Row(row =>
            {
                row.ConstantItem(100).Text("Subtotal:");
                row.ConstantItem(100).AlignRight().Text(order.Subtotal.ToString("N2"));
            });
            col.Item().Row(row =>
            {
                row.ConstantItem(100).Text("Discount:");
                row.ConstantItem(100).AlignRight().Text(order.DiscountAmount.ToString("N2"));
            });
            col.Item().Row(row =>
            {
                row.ConstantItem(100).Text("Tax:");
                row.ConstantItem(100).AlignRight().Text(order.TaxAmount.ToString("N2"));
            });
            col.Item().PaddingTop(3).Row(row =>
            {
                row.ConstantItem(100).Text("Total:").Bold();
                row.ConstantItem(100).AlignRight().Text(order.TotalAmount.ToString("N2")).Bold();
            });
        });
    }

    private static void ComposePaymentInfo(IContainer container, Order order)
    {
        var payment = order.Payment;
        if (payment is null) return;

        var methodDescription = payment.Method switch
        {
            PaymentMethod.Cash => "Cash",
            PaymentMethod.Card => $"Card (Ref: {payment.TransactionReference})",
            PaymentMethod.Mfs => $"{payment.MfsProvider} (Ref: {payment.TransactionReference})",
            _ => payment.Method.ToString()
        };

        container.Column(col =>
        {
            col.Item().Text("Payment Information").Bold();
            col.Item().Text($"Method: {methodDescription}");
            col.Item().Text($"Amount Paid: {payment.AmountPaid:N2}");
            col.Item().Text($"Status: {payment.Status}");
            col.Item().Text($"Date: {payment.PaymentDate:yyyy-MM-dd HH:mm} UTC");
        });
    }
}
